import React from 'react';

export const INDIAN_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Others'
];

export const PRODUCTS = [
  "iPhone 17",
  "iPhone 17 Pro",
  "iPhone 17 Pro Max",
  "iPhone Air",
  "Apple Watch Series 11",
  "Apple Watch Ultra 3",
  "Apple Watch SE (3rd generation)",
  "AirPods Pro 3",
  "AirPods 4 (ANC)",
  "AirPods 4",
  "AirPods Max (2nd generation)",
  "HomePod mini",
  "MacBook Pro (M5)",
  "MacBook Air (M3 / M4)",
  "Mac mini (M4)",
  "Mac Studio",
  "iMac",
  "iPad Pro 11-inch",
  "iPad Pro 13-inch",
  "iPad Air",
  "iPad mini",
  "iPad (standard)",
  "Apple TV 4K",
  "HomePod mini",
  "Apple Vision Pro",
  "MagSafe Charger",
  "Magic Keyboard",
  "EarPods",
  "Apple Pencil"
];

export const STATUSES = [
  { value: 'pending', label: 'Pending' },
  { value: 'pickup_scheduled', label: 'Pickup Scheduled / Pending Pickup' },
  { value: 'origin_scan', label: 'Origin Scan / Arrived at Facility' },
  { value: 'processed_at_hub', label: 'Processed at Hub' },
  { value: 'transshipment', label: 'Transshipment' },
  { value: 'discharged_at_port', label: 'Discharged at Port' },
  { value: 'gate_in_out', label: 'Gate-In / Gate-Out' },
  { value: 'blank_sailing', label: 'Blank Sailing' },
  { value: 'held_in_customs', label: 'Held in Customs / Pending Customs' },
  { value: 'under_assessment', label: 'Under Assessment' },
  { value: 'boe_filed', label: 'Bill of Entry (BOE) Filed' },
  { value: 'customs_cleared', label: 'Customs Cleared / International Shipment Release' },
  { value: 'awaiting_duties_payment', label: 'Awaiting Payment of Duties' },
  { value: 'in_transit', label: 'In Transit' },
  { value: 'arrived_destination_hub', label: 'Arrived at Destination Hub' },
  { value: 'out_for_delivery', label: 'Out for Delivery' },
  { value: 'delivery_attempted', label: 'Delivery Attempted' },
  { value: 'delivered', label: 'Delivered' },
  { value: 'cancelled', label: 'Cancelled' }
];
